# AWSIM ROSbag 記録設定ファイル例

# 出力パス (必須)
output_path: "./recorded_bags"

# 記録対象トピック (必須)
topics:
  - /camera/image_raw
  - /lidar/points
  - /imu/data
  - /gnss/fix
  - /vehicle/status
  - /planning/trajectory
  - /control/cmd_vel

# オプション設定

# 圧縮モード (none, file, message)
compression: "file"

# ストレージ形式 (sqlite3, mcap)
storage_id: "sqlite3"

# 最大バッグサイズ (MB)
max_bag_size: 1024

# 最大記録時間 (秒)
max_bag_duration: 300
